CXX = g++
CXXFLAGS = -g -I./src/ -Wall

OBJ = $(SRC:.cpp=.o)
DEPS = $(SRC:.cpp=.d)

all: $(BIN)

$(BIN): $(OBJ) $(RES)
	$(CXX) $(OBJ) $(LIBS) $(RES) $(CXXFLAGS) -o $(BIN)

clean:
	-rm $(BIN) $(OBJ) $(DEPS) $(RES)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -MD -c $< -o $@

ifneq "$(MAKECMDGOALS)" "clean"
-include $(DEPS)
endif

