
CXX = g++
CXXFLAGS = -g -I./src/
MAKEDEPEND = $(CXX) -MM $(CXXFLAGS) -o $*.d $<
define MAKEDEPEND
	$(CXX) $(CXXFLAGS) -MM -MF $3 -MP -MT $2 $1
endef

OBJ = $(SRC:.cpp=.o)
DEPS = $(SRC:.cpp=.d)

all: $(BIN)

$(BIN): $(OBJ)
	$(CXX) $(OBJ) $(LIBS) $(CXXFLAGS) -o $(BIN)

clean:
	-rm $(BIN)
	-rm $(OBJ)

%.o: %.cpp
	$(call MAKEDEPEND,$<,$@,$(subst .o,.d,$@))
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifneq "$(MAKECMDGOALS)" "clean"

  -include $(DEPS)

endif

