
CXX = g++
CXXFLAGS = -g -I./src/
define MAKEDEPEND
	$(CXX) $(CXXFLAGS) -MM -MF $3 -MP -MT $2 $1
endef

OBJ = $(SRC:.cpp=.o)
DEPS = $(SRC:.cpp=.d)

all: $(BIN)

$(BIN): $(OBJ) $(RES)
	$(CXX) $(OBJ) $(LIBS) $(RES) $(CXXFLAGS) -o $(BIN)

clean:
	-rm $(BIN) $(OBJ) $(DEPS) $(RES)

%.o: %.cpp
	$(call MAKEDEPEND,$<,$@,$(subst .o,.d,$@))
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifneq "$(MAKECMDGOALS)" "clean"

  -include $(DEPS)

endif

