set(SRC
	${SRC}
	../game/chassis.cpp
	../game/crankshaft.cpp
	../game/cylinderblock.cpp
	../game/cylinderhead.cpp
	../game/object.cpp
	../game/objectfactory.cpp
	../game/part.cpp
	../game/partcontainer.cpp
	../game/player.cpp
	../game/serializable.cpp
	../game/state.cpp
	../game/transmission.cpp
	../game/vehicle.cpp
)
