#ifndef UI_HPP
#define UI_HPP

#include "graphics/vector2d.hpp"

const float PADDING=0.02;
const float ITEM_HEIGHT=0.05;

const Vector2D BACK_BUTTON_POSITION(PADDING,1.0-ITEM_HEIGHT-PADDING);
const Vector2D NEXT_BUTTON_POSITION(0.5,1.0-ITEM_HEIGHT-PADDING);
const Vector2D BUTTON_HEIGHT(0.0,ITEM_HEIGHT+0.005);

const Vector2D TITLE_POSITION(PADDING,PADDING);
const Vector2D TITLE_SIZE(0.96,0.1);
const Vector2D CONTENT_POSITION(PADDING,PADDING*2+TITLE_SIZE.getY());
const Vector2D FIELD_SIZE(0.5-PADDING,ITEM_HEIGHT);

#endif // UI_HPP
